title: Dahee's blog
author: Dahee 
email: teg0930@sookmyung.ac.kr
description: >- this is my portfolio. # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dahee00.github.io" 
show_excerpts: true

#twitter_username: jekyllrb
github_username:  dahee song



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

sass:
  sass_dir: _sass
plainwhite:
  name: Dahee Song
  tagline: Computer Science. Mechanical Engineering
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/portfolio.png" 
  html_lang: "en" 
  condensed_mobile:
    #- home
    - page
    - post

  # generate social links in footer
  social_links:
    github:  https://github.com/dahee00.github.io
    instagram: "www.instagram.com/daheess_
    email: teg0930@sookmyung.ac.kr

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag

